### ISSUE TITLE
Requierement.txt

### ISSUE THREAD

**Issue by salihbilgin** [CodeEnvironment/django-rest-framework-code#1]
Hello,
I prepared the requi.txt file for those who pulled the project. You can add if you want.
[req.txt](https://github.com/CodeEnvironment/django-rest-framework-code/files/5649338/req.txt)
Regards.

**Comment by CodeEnvironment** [comment]
Hello Salih,
Thank you for taking initiative, I'll add it for sure.

Best regards

**Comment by CodeEnvironment** [comment]
requirements.txt has been added
